# Generated by Django 4.0.1 on 2024-02-15 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model_training', '0002_alter_trainedneuralnetwork_neural_network_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedneuralnetwork',
            name='user',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='trained_neural_networks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
