# Generated by Django 5.0 on 2024-04-17 11:43

import datetime
import django.core.validators
import django.db.models.deletion
import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_inference', '0007_remove_inferredkeypoints_trained_neural_network'),
        ('model_training', '0003_trainedneuralnetwork_user'),
        ('train_datasets_manager', '0005_remove_skeletonkeypoint_skeleton_delete_skeleon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainedneuralnetwork',
            name='neural_network_type',
        ),
        migrations.RemoveField(
            model_name='trainedneuralnetwork',
            name='train_dataset',
        ),
        migrations.RemoveField(
            model_name='trainedneuralnetwork',
            name='user',
        ),
        migrations.CreateModel(
            name='DLCNeuralNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_uid', models.CharField(max_length=500)),
                ('started_training_at', models.DateTimeField(default=datetime.datetime.now)),
                ('finished_training_at', models.DateTimeField(blank=True, null=True)),
                ('test_fraction', models.FloatField(validators=[django.core.validators.MinValueValidator(0), utils.validators.less_1])),
                ('num_epochs', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('backbone_model', models.CharField(choices=[('resnet_50', 'ResNet 50'), ('resnet_101', 'ResNet 101'), ('resnet_152', 'ResNet 152'), ('mobilenet_v2_1.0', 'MobileNet v2-1.0'), ('mobilenet_v2_0.75', 'MobileNet v2-0.75'), ('mobilenet_v2_0.5', 'MobileNet v2-0.5'), ('mobilenet_v2_0.35', 'MobileNet v2-0.35')])),
                ('train_dataset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dlc_neural_networks', to='train_datasets_manager.traindataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlc_neural_networks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SLEAPNeuralNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_uid', models.CharField(max_length=500)),
                ('started_training_at', models.DateTimeField(default=datetime.datetime.now)),
                ('finished_training_at', models.DateTimeField(blank=True, null=True)),
                ('test_fraction', models.FloatField(validators=[django.core.validators.MinValueValidator(0), utils.validators.less_1])),
                ('num_epochs', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('learning_rate', models.FloatField(validators=[utils.validators.greater_0])),
                ('backbone_model', models.CharField(choices=[('unet', 'UNet'), ('leap', 'LEAP'), ('hourglass', 'Hourglass'), ('resnet', 'ResNet'), ('pretrained_encoder', 'Pretrained encoder')])),
                ('pretrained_encoder', models.CharField(blank=True, choices=[('vgg16', 'vgg16'), ('vgg19', 'vgg19'), ('resnet18', 'resnet18'), ('resnet34', 'resnet34'), ('resnet50', 'resnet50'), ('resnet101', 'resnet101'), ('resnet152', 'resnet152'), ('resnext50', 'resnext50'), ('resnext101', 'resnext101'), ('inceptionv3', 'inceptionv3'), ('inceptionresnetv2', 'inceptionresnetv2'), ('densenet121', 'densenet121'), ('densenet169', 'densenet169'), ('densenet201', 'densenet201'), ('seresnet18', 'seresnet18'), ('seresnet34', 'seresnet34'), ('seresnet50', 'seresnet50'), ('seresnet101', 'seresnet101'), ('seresnet152', 'seresnet152'), ('seresnext50', 'seresnext50'), ('seresnext101', 'seresnext101'), ('senet154', 'senet154'), ('mobilenet', 'mobilenet'), ('mobilenetv2', 'mobilenetv2'), ('efficientnetb0', 'efficientnetb0'), ('efficientnetb1', 'efficientnetb1'), ('efficientnetb2', 'efficientnetb2'), ('efficientnetb3', 'efficientnetb3'), ('efficientnetb4', 'efficientnetb4'), ('efficientnetb5', 'efficientnetb5')], null=True)),
                ('heads_sigma', models.FloatField(validators=[utils.validators.greater_0])),
                ('heads_output_stride', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('train_dataset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sleap_neural_networks', to='train_datasets_manager.traindataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleap_neural_networks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='NeuralNetworkType',
        ),
        migrations.DeleteModel(
            name='TrainedNeuralNetwork',
        ),
    ]
