# Generated by Django 5.0 on 2024-04-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_training', '0004_remove_trainedneuralnetwork_neural_network_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlcneuralnetwork',
            name='neural_network_type',
            field=models.CharField(default='DLC'),
        ),
        migrations.AddField(
            model_name='sleapneuralnetwork',
            name='neural_network_type',
            field=models.CharField(default='SLEAP'),
        ),
    ]
