# Generated by Django 4.0.1 on 2024-02-12 16:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import video_manager.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video_manager', '0003_rename_file_path_inferencevideo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inferencevideo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inferencevideo',
            name='file',
            field=models.FileField(upload_to=video_manager.models.inference_video_upload_path, validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov'])]),
        ),
        migrations.AlterField(
            model_name='inferencevideo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
