# Generated by Django 4.0.1 on 2024-02-15 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model_inference', '0002_alter_inferredkeypoints_inference_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferredkeypoints',
            name='user',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='inferred_keypoints_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
