# Generated by Django 4.0.1 on 2024-04-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_inference', '0004_alter_inferredkeypoints_keypoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inferredkeypoints',
            name='keypoints',
        ),
        migrations.AddField(
            model_name='inferredkeypoints',
            name='results_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
