# Generated by Django 4.0.1 on 2024-04-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_inference', '0005_remove_inferredkeypoints_keypoints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferredkeypoints',
            name='keypoints',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
