# Generated by Django 5.0 on 2024-04-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_inference', '0006_inferredkeypoints_keypoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inferredkeypoints',
            name='trained_neural_network',
        ),
    ]
