# Generated by Django 5.0 on 2024-04-17 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_inference', '0007_remove_inferredkeypoints_trained_neural_network'),
        ('model_training', '0004_remove_trainedneuralnetwork_neural_network_type_and_more'),
        ('video_manager', '0004_alter_inferencevideo_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inferredkeypoints',
            name='dlc_neural_network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inferred_keypoints_set', to='model_training.dlcneuralnetwork'),
        ),
        migrations.AddField(
            model_name='inferredkeypoints',
            name='sleap_neural_network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inferred_keypoints_set', to='model_training.sleapneuralnetwork'),
        ),
        migrations.AddConstraint(
            model_name='inferredkeypoints',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('sleap_neural_network__isnull', True), ('dlc_neural_network__isnull', True), _connector='OR'), models.Q(('sleap_neural_network__isnull', False), ('dlc_neural_network__isnull', False), _connector='OR')), name='only_one_neural_network'),
        ),
    ]
