# Generated by Django 5.0 on 2024-04-30 10:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_inference', '0008_inferredkeypoints_dlc_neural_network_and_more'),
        ('model_training', '0006_alter_dlcneuralnetwork_train_dataset_and_more'),
        ('video_manager', '0004_alter_inferencevideo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inferredkeypoints',
            name='dlc_neural_network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inferred_keypoints_set', to='model_training.dlcneuralnetwork'),
        ),
        migrations.AlterField(
            model_name='inferredkeypoints',
            name='inference_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inferred_keypoints_set', to='video_manager.inferencevideo'),
        ),
        migrations.AlterField(
            model_name='inferredkeypoints',
            name='sleap_neural_network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inferred_keypoints_set', to='model_training.sleapneuralnetwork'),
        ),
        migrations.CreateModel(
            name='LabeledVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_production_at', models.DateTimeField(default=datetime.datetime.now)),
                ('finished_production_at', models.DateTimeField(blank=True, null=True)),
                ('file_path', models.CharField()),
                ('analysis_results', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='labeled_video', to='model_inference.inferredkeypoints')),
            ],
        ),
    ]
